# Generated by Django 5.2.7 on 2026-03-05 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='pictures')),
                ('name', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('career', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'Everyone can see'), ('shared', 'Someone can see'), ('private', 'Nobody')], max_length=100)),
                ('data', models.JSONField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.node')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(blank=True, max_length=100, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_child', to='main.node')),
                ('father', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_father', to='main.node')),
            ],
        ),
    ]
