# Generated by Django 5.2.7 on 2026-06-25 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_public',
            field=models.BooleanField(default=False, help_text='اگه حساب عمومی باشه، این نود برای دیگران قابل مشاهده\u200cست', verbose_name='عمومی'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='is_public',
            field=models.BooleanField(default=False, help_text='اگه حساب عمومی باشه، این رابطه برای دیگران قابل مشاهده\u200cست', verbose_name='عمومی'),
        ),
    ]
