# Generated by Django 5.2.7 on 2026-03-16 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_node_career_alter_node_name_alter_node_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informations', to='main.node'),
        ),
        migrations.AlterField(
            model_name='information',
            name='visibility',
            field=models.CharField(choices=[('public', 'Everyone can see'), ('shared', 'Someone can see'), ('private', 'Nobody')], default='private', max_length=10),
        ),
        migrations.AlterField(
            model_name='node',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
