# Generated by Django 5.2.7 on 2026-06-26 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_v3_bugfixes_features'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appsettings',
            options={'verbose_name': 'تنظیمات (قدیمی)', 'verbose_name_plural': 'تنظیمات (قدیمی)'},
        ),
    ]
