# Generated by Django 5.2.7 on 2026-03-16 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_information_node_alter_information_visibility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
