# Generated by Django 5.2.7 on 2026-06-25 19:55

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_public', models.BooleanField(default=False, help_text='شبکه\u200cات برای دیگران قابل جستجو باشه', verbose_name='حساب عمومی')),
                ('trust_score', models.IntegerField(default=80, verbose_name='امتیاز اعتماد')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='آواتار')),
                ('bio', models.TextField(blank=True, verbose_name='درباره من')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('career', models.CharField(blank=True, max_length=200, verbose_name='شغل')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='شهر')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='کشور')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام گروه')),
                ('color', models.CharField(blank=True, help_text='کد رنگ hex مثل #6366f1 (اختیاری)', max_length=20, verbose_name='رنگ')),
                ('is_public', models.BooleanField(default=False, help_text='این گروه برای کاربران دیگه قابل مشاهده\u200cست', verbose_name='عمومی')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups_owned', to=settings.AUTH_USER_MODEL, verbose_name='صاحب')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن')),
                ('entry_date', models.DateField(blank=True, null=True, verbose_name='تاریخ رویداد')),
                ('tags', models.JSONField(blank=True, default=list, verbose_name='تگ\u200cها')),
                ('mood', models.CharField(blank=True, max_length=100, verbose_name='خلق\u200cوخو')),
                ('ai_analyzed', models.BooleanField(default=False, verbose_name='آنالیز AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL, verbose_name='صاحب')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal/', verbose_name='تصویر')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.journalentry')),
            ],
            options={
                'verbose_name': 'یادداشت روزانه',
                'verbose_name_plural': 'یادداشت\u200cهای روزانه',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(blank=True, max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=100, verbose_name='نام خانوادگی')),
                ('nickname', models.CharField(blank=True, max_length=100, verbose_name='لقب / اسم مستعار')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('career', models.CharField(blank=True, max_length=200)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('group', models.CharField(blank=True, help_text='legacy — از groups استفاده کن', max_length=100, verbose_name='گروه (قدیمی)')),
                ('username_locked', models.BooleanField(default=False, help_text='نودی که از حساب عمومی import شده', verbose_name='یوزرنیم قفل\u200cشده')),
                ('groups', models.ManyToManyField(blank=True, related_name='nodes', to='main.group', verbose_name='گروه\u200cها')),
                ('imported_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exported_nodes', to=settings.AUTH_USER_MODEL, verbose_name='وارد شده از')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to=settings.AUTH_USER_MODEL, verbose_name='صاحب')),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.AddField(
            model_name='journalentry',
            name='mentioned_nodes',
            field=models.ManyToManyField(blank=True, related_name='journal_entries', to='main.node'),
        ),
        migrations.CreateModel(
            name='Information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('public', 'Everyone can see'), ('shared', 'Someone can see'), ('private', 'Nobody')], default='private', max_length=10)),
                ('data', models.JSONField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='informations', to='main.node')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='صاحب')),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to='main.node')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='as_root', to='main.node', verbose_name='نود اصلی (من)')),
            ],
            options={
                'verbose_name': 'تنظیمات',
                'verbose_name_plural': 'تنظیمات',
            },
        ),
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(db_index=True, max_length=120)),
                ('alert_type', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('action', models.CharField(choices=[('completed', 'انجام دادم'), ('dismissed', 'رد کردم')], default='dismissed', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_actions', to=settings.AUTH_USER_MODEL, verbose_name='صاحب')),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_actions', to='main.node')),
            ],
            options={
                'verbose_name': 'اقدام روی هشدار',
                'verbose_name_plural': 'اقدامات روی هشدارها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notif_type', models.CharField(choices=[('system', 'سیستمی'), ('sync', 'همگام\u200cسازی'), ('trust', 'امتیاز اعتماد'), ('alert', 'هشدار')], default='system', max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('link', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'اطلاعیه',
                'verbose_name_plural': 'اطلاعیه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_username', models.CharField(max_length=100)),
                ('event_type', models.CharField(default='new_data', max_length=30)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('accepted', 'قبول شد'), ('ignored', 'نادیده'), ('flagged', 'اشتباه')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_syncs', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'همگام\u200cسازی',
                'verbose_name_plural': 'همگام\u200cسازی\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel', models.CharField(blank=True, max_length=100, null=True)),
                ('strength', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('distant', 'دور شده'), ('inactive', 'غیرفعال')], default='active', max_length=10)),
                ('met_at', models.DateField(blank=True, null=True, verbose_name='تاریخ آشنایی')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to=settings.AUTH_USER_MODEL, verbose_name='صاحب')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_source', to='main.node')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_target', to='main.node')),
            ],
            options={
                'unique_together': {('source', 'target', 'rel')},
            },
        ),
    ]
