# Generated by Django 5.2.7 on 2026-03-16 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='career',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='node',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='nodes/'),
        ),
        migrations.AlterField(
            model_name='node',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='relationship',
            unique_together={('father', 'child', 'rel')},
        ),
    ]
