# Generated by Django 5.2.7 on 2026-06-19 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_relationship_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_source', to='main.node'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='as_target', to='main.node'),
        ),
    ]
