# Generated by Django 5.2.7 on 2026-06-20 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_relationship_source_alter_relationship_target'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='met_at',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ آشنایی'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='status',
            field=models.CharField(choices=[('active', 'فعال'), ('distant', 'دور شده'), ('inactive', 'غیرفعال')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='relationship',
            name='strength',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='events', to='main.node')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
