# Generated by Django 5.2.15 on 2026-07-03 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_followup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AlterField(
            model_name='interaction',
            name='kind',
            field=models.CharField(choices=[('call', '📞 تلفنی'), ('meet', '🤝 حضوری'), ('message', '💬 پیام'), ('online', '🌐 آنلاین'), ('journal', '📓 از ژورنال'), ('checkin', '⚡ چک-این'), ('other', '✦ سایر')], default='call', max_length=15, verbose_name='نوع'),
        ),
    ]
