# Generated by Django 5.2.7 on 2026-06-24 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_journalentry_tags_mood_analyzed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journalentry',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='journalimage',
            options={'ordering': ['uploaded_at'], 'verbose_name': 'یادداشت روزانه', 'verbose_name_plural': 'یادداشت\u200cهای روزانه'},
        ),
        migrations.CreateModel(
            name='AlertAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.CharField(db_index=True, max_length=120)),
                ('alert_type', models.CharField(blank=True, max_length=50)),
                ('title', models.CharField(blank=True, max_length=300)),
                ('action', models.CharField(choices=[('completed', 'انجام دادم'), ('dismissed', 'رد کردم')], default='dismissed', max_length=20)),
                ('outcome', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alert_actions', to='main.node')),
            ],
            options={
                'verbose_name': 'اقدام روی هشدار',
                'verbose_name_plural': 'اقدامات روی هشدارها',
                'ordering': ['-created_at'],
            },
        ),
    ]
