# Generated by Django 5.2.7 on 2026-06-24 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_journalentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='group',
            field=models.CharField(blank=True, help_text='مثال: خانواده، کار، دوستان، داستان', max_length=100, verbose_name='گروه'),
        ),
    ]
