# Generated by Django 5.2.7 on 2026-06-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_node_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام گروه')),
                ('color', models.CharField(blank=True, help_text='کد رنگ hex مثل #6366f1 (اختیاری)', max_length=20, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'گروه',
                'verbose_name_plural': 'گروه\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='node',
            name='group',
            field=models.CharField(blank=True, help_text='legacy — از groups استفاده کن', max_length=100, verbose_name='گروه (قدیمی)'),
        ),
        migrations.AddField(
            model_name='node',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='nodes', to='main.group', verbose_name='گروه\u200cها'),
        ),
    ]
