# Generated by Django 5.2.4 on 2026-08-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_social_public_layer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemediaitem',
            name='is_public',
            field=models.BooleanField(default=True, help_text='فالوئرها و بازدیدکنندگان فقط آثار عمومی را می\u200cبینند', verbose_name='نمایش در پروفایل عمومی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_interests',
            field=models.JSONField(blank=True, default=list, help_text='فقط برای پیشنهادهای اجتماعی و پروفایل عمومی استفاده می\u200cشود', verbose_name='علایق عمومی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_values',
            field=models.JSONField(blank=True, default=list, help_text='فقط برای پیشنهادهای اجتماعی و پروفایل عمومی استفاده می\u200cشود', verbose_name='ارزش\u200cهای عمومی'),
        ),
    ]
