# Generated by Django 5.2.4 on 2026-08-06 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_profilemediaitem_is_public_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialCircle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_circles_created', to=settings.AUTH_USER_MODEL)),
                ('members', models.ManyToManyField(blank=True, related_name='social_circles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'حلقه اجتماعی',
                'verbose_name_plural': 'حلقه\u200cهای اجتماعی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialCircleMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=2000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_circle_messages', to=settings.AUTH_USER_MODEL)),
                ('circle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='main.socialcircle')),
            ],
            options={
                'verbose_name': 'پیام حلقه اجتماعی',
                'verbose_name_plural': 'پیام\u200cهای حلقه اجتماعی',
                'ordering': ['created_at'],
            },
        ),
    ]
