# Generated by Django 5.2.4 on 2026-08-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_merge_social_and_giftbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='entry_kind',
            field=models.CharField(choices=[('moment', 'لحظه'), ('reflection', 'جمع\u200cبندی روز')], default='reflection', max_length=12, verbose_name='نوع ثبت'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان رخداد'),
        ),
    ]
