# Generated by Django 5.2.4 on 2026-08-06 19:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_journalentry_entry_kind_journalentry_occurred_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelationshipPulse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.PositiveSmallIntegerField(default=3)),
                ('autonomy', models.PositiveSmallIntegerField(default=3)),
                ('belonging', models.PositiveSmallIntegerField(default=3)),
                ('trust', models.PositiveSmallIntegerField(default=3)),
                ('voice', models.PositiveSmallIntegerField(default=3)),
                ('note', models.CharField(blank=True, max_length=280)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relationship_pulses', to='main.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_pulses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
