# Generated by Django 5.2.4 on 2026-08-06 19:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_relationshippulse'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('kind', models.CharField(max_length=20)),
                ('payload', models.JSONField(default=dict)),
                ('status', models.CharField(default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
