# Generated by Django 5.2.4 on 2026-08-06 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_extractionsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractionsuggestion',
            name='applied_model',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='extractionsuggestion',
            name='applied_object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='extractionsuggestion',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='extractionsuggestion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_chat_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_checkin_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_extraction_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='ai_journal_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddConstraint(
            model_name='extractionsuggestion',
            constraint=models.UniqueConstraint(condition=models.Q(('fingerprint', ''), _negated=True), fields=('owner', 'source', 'source_id', 'fingerprint'), name='unique_extraction_per_source'),
        ),
    ]
