# Generated by Django 5.2.4 on 2026-08-06 22:16

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_extractionsuggestion_applied_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('interest', 'علاقه'), ('value', 'ارزش'), ('communication', 'سبک ارتباطی'), ('boundary', 'مرز'), ('sensitivity', 'حساسیت'), ('preference', 'ترجیح'), ('life_topic', 'موضوع زندگی'), ('emotion', 'محرک احساسی'), ('other', 'سایر')], max_length=20)),
                ('value', models.CharField(max_length=300)),
                ('confidence', models.PositiveSmallIntegerField(default=70)),
                ('source', models.CharField(max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('observed_at', models.DateTimeField(default=django.db.models.functions.datetime.Now)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_facts', to='main.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memory_facts', to=settings.AUTH_USER_MODEL)),
                ('suggestion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memory_facts', to='main.extractionsuggestion')),
            ],
            options={
                'ordering': ['category', '-confidence', '-observed_at'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'node', 'category', 'value'), name='unique_memory_fact_per_node')],
            },
        ),
        migrations.CreateModel(
            name='NodeAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('normalized_alias', models.CharField(db_index=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='main.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('owner', 'normalized_alias'), name='unique_node_alias_per_owner')],
            },
        ),
    ]
