# Generated by Django 5.2.4 on 2026-08-06 22:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_memoryfact_nodealias'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryfact',
            name='ai_usable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='memoryfact',
            name='superseded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superseded_facts', to='main.memoryfact'),
        ),
        migrations.AddField(
            model_name='node',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_duplicates', to='main.node'),
        ),
        migrations.CreateModel(
            name='NodeMergeOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snapshot', models.JSONField(default=dict)),
                ('status', models.CharField(default='applied', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('undone_at', models.DateTimeField(blank=True, null=True)),
                ('duplicate_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_operations_duplicate', to='main.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_merge_operations', to=settings.AUTH_USER_MODEL)),
                ('primary_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_operations_primary', to='main.node')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(default='connect', max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('suggestion', models.TextField()),
                ('reason', models.TextField(blank=True)),
                ('status', models.CharField(default='active', max_length=15)),
                ('snoozed_until', models.DateField(blank=True, null=True)),
                ('outcome', models.CharField(blank=True, max_length=20)),
                ('outcome_note', models.CharField(blank=True, max_length=300)),
                ('helpful', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acted_at', models.DateTimeField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='main.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
