# Generated by Django 5.2.4 on 2026-08-06 22:56

import django.db.models.deletion
import django.db.models.functions.datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_memoryfact_ai_usable_memoryfact_superseded_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memoryfact',
            name='confidentiality',
            field=models.CharField(choices=[('normal', 'معمولی'), ('personal', 'شخصی'), ('sensitive', 'بسیار حساس'), ('financial', 'مالی'), ('health', 'سلامت'), ('no_ai', 'ممنوع برای AI')], default='personal', max_length=15),
        ),
        migrations.CreateModel(
            name='Commitment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible', models.CharField(choices=[('me', 'من'), ('them', 'طرف مقابل')], max_length=10)),
                ('text', models.CharField(max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='open', max_length=12)),
                ('source', models.CharField(default='manual', max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to='main.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commitments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', 'due_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftIdea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('occasion', models.CharField(blank=True, max_length=100)),
                ('budget', models.PositiveBigIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='idea', max_length=15)),
                ('notes', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_ideas', to='main.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_ideas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingReflection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateTimeField(default=django.db.models.functions.datetime.Now)),
                ('summary', models.TextField()),
                ('feeling', models.SmallIntegerField(default=0)),
                ('relationship_change', models.CharField(default='same', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reflections', to='main.event')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reflections', to='main.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_reflections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NodeSafetySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pause_contact_suggestions', models.BooleanField(default=False)),
                ('no_contact_until', models.DateField(blank=True, null=True)),
                ('hide_emotional_reminders', models.BooleanField(default=False)),
                ('boundaries', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('node', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_setting', to='main.node')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='node_safety_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
