# Generated by Django 5.2.4 on 2026-08-06 23:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_memoryfact_confidentiality_commitment_giftidea_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExtractionTrace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('input_text', models.TextField(blank=True)),
                ('regex_output', models.JSONField(default=list)),
                ('ai_output', models.JSONField(default=list)),
                ('merged_output', models.JSONField(default=list)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('model_name', models.CharField(blank=True, max_length=100)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='regex_only', max_length=20)),
                ('error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(max_length=80, unique=True)),
                ('label', models.CharField(max_length=160)),
                ('enabled', models.BooleanField(default=False)),
                ('staff_only', models.BooleanField(default=False)),
                ('rollout_percent', models.PositiveSmallIntegerField(default=100)),
                ('description', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='KnowledgeTriple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicate', models.CharField(max_length=80)),
                ('object_text', models.CharField(blank=True, max_length=300)),
                ('confidence', models.PositiveSmallIntegerField(default=70)),
                ('source', models.CharField(max_length=20)),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ObservabilityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(db_index=True, max_length=36)),
                ('level', models.CharField(default='error', max_length=10)),
                ('area', models.CharField(default='backend', max_length=40)),
                ('path', models.CharField(blank=True, max_length=240)),
                ('code', models.CharField(blank=True, max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='node',
            name='is_demo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='demo_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='extractionsuggestion',
            index=models.Index(fields=['owner', 'status', '-created_at'], name='extract_owner_status'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['owner', '-created_at'], name='journal_owner_created'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['owner', 'entry_date'], name='journal_owner_date'),
        ),
        migrations.AddIndex(
            model_name='memoryfact',
            index=models.Index(fields=['owner', 'node', 'active'], name='memory_owner_node_active'),
        ),
        migrations.AddField(
            model_name='aiextractiontrace',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_extraction_traces', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgetriple',
            name='object_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_objects', to='main.node'),
        ),
        migrations.AddField(
            model_name='knowledgetriple',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_triples', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='knowledgetriple',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_subjects', to='main.node'),
        ),
        migrations.AddField(
            model_name='observabilityevent',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observability_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='aiextractiontrace',
            index=models.Index(fields=['owner', '-created_at'], name='ai_trace_owner_created'),
        ),
        migrations.AddIndex(
            model_name='knowledgetriple',
            index=models.Index(fields=['owner', 'predicate'], name='knowledge_owner_pred'),
        ),
        migrations.AddConstraint(
            model_name='knowledgetriple',
            constraint=models.UniqueConstraint(fields=('owner', 'subject', 'predicate', 'object_text', 'object_node'), name='unique_knowledge_triple'),
        ),
        migrations.AddIndex(
            model_name='observabilityevent',
            index=models.Index(fields=['area', '-created_at'], name='obs_area_created'),
        ),
    ]
