# Generated by Django 5.2.4 on 2026-08-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_aiextractiontrace_featureflag_knowledgetriple_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='feature_overrides',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
