# Generated by Django 5.2.4 on 2026-08-06 23:29

from django.db import migrations


def seed_flags(apps, schema_editor):
    FeatureFlag = apps.get_model('main', 'FeatureFlag')
    flags = [
        ('hybrid-ai', 'استخراج ترکیبی AI', False),
        ('psychology-memory', 'حافظه روان‌شناختی', True),
        ('relationship-suggestions', 'پیشنهاد ارتباط', True),
        ('pwa', 'نسخه PWA', True),
        ('social-network', 'شبکه اجتماعی', True),
        ('device-notifications', 'اعلان‌های دستگاه', True),
    ]
    for name, label, enabled in flags:
        FeatureFlag.objects.get_or_create(name=name, defaults={
            'label': label, 'enabled': enabled, 'rollout_percent': 100})


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_user_feature_overrides'),
    ]

    operations = [
        migrations.RunPython(seed_flags, migrations.RunPython.noop),
    ]
