# Generated by Django 5.2.4 on 2026-08-07 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_image_owners(apps, schema_editor):
    JournalImage = apps.get_model('main', 'JournalImage')
    for image in JournalImage.objects.filter(entry__isnull=False, owner__isnull=True).select_related('entry').iterator():
        image.owner_id = image.entry.owner_id
        image.save(update_fields=['owner'])


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_sharelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalimage',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journal_images', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(backfill_image_owners, migrations.RunPython.noop),
    ]
