# Generated by Django 5.2.4 on 2026-08-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_journalimage_owner'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='memoryfact',
            index=models.Index(fields=['owner', 'active'], name='memory_owner_active'),
        ),
    ]
