# Generated by Django 5.2.4 on 2026-08-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_notification_notif_user_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
