# Generated by Django 5.2.4 on 2026-08-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_node_is_pinned'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['owner', 'date'], name='event_owner_date'),
        ),
        migrations.AddIndex(
            model_name='followup',
            index=models.Index(fields=['owner', 'done', 'due_date'], name='follow_owner_done_due'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['owner', 'username'], name='node_owner_username'),
        ),
        migrations.AddIndex(
            model_name='node',
            index=models.Index(fields=['owner', 'merged_into', 'is_pinned'], name='node_owner_merge_pin'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['owner', 'status', '-strength'], name='rel_owner_status_strength'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['owner', 'source'], name='rel_owner_source'),
        ),
        migrations.AddIndex(
            model_name='relationship',
            index=models.Index(fields=['owner', 'target'], name='rel_owner_target'),
        ),
    ]
