# Generated by Django 5.2.4 on 2026-08-30 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_event_event_owner_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaprofile',
            name='previous_statements',
            field=models.JSONField(blank=True, default=list, verbose_name='جملات نسخهٔ قبل'),
        ),
        migrations.AddField(
            model_name='personaprofile',
            name='previous_synth_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان سنتز قبلی'),
        ),
        migrations.AddField(
            model_name='relationshipprofile',
            name='previous_statements',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='relationshipprofile',
            name='previous_synth_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
