# Generated by Django 5.2.4 on 2026-09-04 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='support_kind',
            field=models.CharField(blank=True, choices=[('', '—'), ('heard', '👂 شنیده شدم'), ('info', '💡 اطلاعات / راهنمایی'), ('practical', '🤝 کمک عملی'), ('presence', '🫂 صرفاً بودن')], default='', max_length=10, verbose_name='نوع حمایت'),
        ),
    ]
