# Generated by Django 5.2.4 on 2026-09-04 12:48

import main.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_undoableaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalimage',
            name='image',
            field=models.ImageField(upload_to='journal/', validators=[main.uploads.validate_image_file], verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='node',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/', validators=[main.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='social_posts/', validators=[main.uploads.validate_image_file]),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', validators=[main.uploads.validate_image_file], verbose_name='آواتار'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_covers/', validators=[main.uploads.validate_image_file], verbose_name='بک\u200cگراند پروفایل'),
        ),
    ]
