# Generated by Django 5.2.4 on 2026-09-04 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_alter_journalimage_image_alter_node_picture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIQualityEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suite_version', models.CharField(max_length=80)),
                ('engine_version', models.CharField(max_length=80)),
                ('total_cases', models.PositiveIntegerField(default=0)),
                ('passed_cases', models.PositiveIntegerField(default=0)),
                ('pass_rate', models.FloatField(default=0)),
                ('precision', models.FloatField(default=0)),
                ('recall', models.FloatField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('report', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_quality_evaluations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
