# Generated by Django 5.2.4 on 2026-09-04 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_aiqualityevaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRequestMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(default='chat', max_length=40)),
                ('provider', models.CharField(blank=True, max_length=40)),
                ('requested_model', models.CharField(blank=True, max_length=120)),
                ('actual_model', models.CharField(blank=True, max_length=120)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('deadline_ms', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(default='success', max_length=20)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('fallback_used', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_request_metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['feature', '-created_at'], name='ai_metric_feature_time')],
            },
        ),
    ]
