# Generated by Django 5.2.4 on 2026-09-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_airequestmetric'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='privacy_consent_at',
            field=models.DateTimeField(blank=True, help_text='زمانی که کاربر متن حریم خصوصی و استفاده از AI را پذیرفت', null=True, verbose_name='زمان پذیرش حریم خصوصی'),
        ),
    ]
