# Generated by Django 5.2.4 on 2026-09-05 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_nodecontactdetails_social_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='extracted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='extracted_suggestion_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='extraction_error',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='extraction_status',
            field=models.CharField(choices=[('pending', 'pending'), ('processed', 'processed'), ('disabled', 'disabled'), ('error', 'error')], default='pending', max_length=16),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='mentioned_nodes',
            field=models.ManyToManyField(blank=True, related_name='chat_messages', to='main.node', verbose_name='افراد مرتبط'),
        ),
    ]
